server:
  port: 9090
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 'http://localhost:4200'
            allowedHeaders:
              - Content-Type
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: EQUIPMENT-SERVICE
          uri:
            lb://EQUIPMENT-SERVICE
          predicates:
            - Path=/Equipment/**
          filters:
            - AutenticationFilter
        - id: AUTH-SERVICE
          uri:
            lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
