server:
  port: 9090
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: EQUIPMENT-SERVICE
          uri:
            lb://EQUIPMENT-SERVICE
          predicates:
            - Path=/Equipment/**
          filters:
            - AutenticationFilter
        - id: AUTH-SERVICE
          uri:
            lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
